# Top 50 programers at Sairam Eningeering college ranked based on skillrack scores 

### (Updated Aug 10 2020)

# Import BeautifulSoup and Panda

In [9]:
from bs4 import BeautifulSoup as bs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#for getting from the internet use request
#import requests as rs

# Load page

In [10]:
soup = bs(open("skillrackdata.html"))

In [11]:
#print(soup.prettify()) #to preview the code

In [12]:
table=soup.select("td.gridcell") 

name=[]
dept=[] 
ID=[]
gold=[] 
silver=[] 
bronze=[]

for i in range(100):
    if i%2==0:
        c=0
        for j in table[i].stripped_strings:
            if c==0:
                name.append(j)
                c+=1
                continue
            if c==1:
                dept.append(j)
                c+=1
                continue
            if c==2:
                ID.append(j)
                c=0
                continue
    else:
        c=0
        for j in table[i].stripped_strings:
            if c==0 and j.isdigit():
                gold.append(j)
                c+=1 
                continue
            if c==1 and j.isdigit():
                silver.append(j)
                c+=1 
                continue
            if c==2 and j.isdigit():
                bronze.append(j)
                c=0
                continue
result=[]
for i in range(len(name)):
    value=[]
    value.append(name[i])
    value.append(dept[i])
    value.append(ID[i])
    value.append(int(gold[i]))
    value.append(int(silver[i]))
    value.append(int(bronze[i]))
    result.append(value)

df=pd.DataFrame(result,columns=["Name","Dept","ID","Gold","Silver","Bronze"])
df.columns.name = 'Rank'
df.index = df.index + 1
df

Rank                   Name  Dept          ID  Gold  Silver  Bronze
1               MUKILAN I K   CSE     E8CS129     0       2     966
2            NATHAN DRAKE $   CSE     E8CS059     0       1    1070
3                  VIKRAM V   CSE     E8CS014     0       1     714
4               SHIBANIKA R   CSE     E8CS111     0       0    2437
5         EYUWANKG S SWANKG   CSE     E8CS124     0       0    2219
6                KARTHIKA A    IT     E8IT079     0       0    2006
7         SURESH KRISHNAA R   CSE     E8CS005     0       0    1947
8              VISHWAJITH V   CSE     E8CS094     0       0    1939
9             PARTHIBARAJ G   CSE     E8CS088     0       0    1895
10            SAKTHIVELAN S   CSE     E8CS078     0       0    1894
11              VENKATESH D   CSE     E8CS050     0       0    1690
12         KARTHIK PRASAD T   CSE     E8CS041     0       0    1678
13             MADHUMITHA S   CSE     E8CS068     0       0    1549
14               SANTHOSH T    IT     E8IT005     0       0    1522
15            VIMAL KUMAR V   CSE     E8CS121     0       0    1512
16               ANIRUDDH R  PROD     E8PR006     0       0    1488
17                 KAVI KON   CSE     E8CS119     0       0    1480
18            VISWANATHAN M    IT     E8IT016     0       0    1444
19    N.MOHAMED SAYHANUDDIN    IT     E8IT061     0       0    1417
20             VIGNESHWAR B    IT     E8IT019     0       0    1328
21                 NAVIN SK   EEE     E8EE006     0       0    1327
22          HRITHIK KUMAR V   ECE     E8EC013     0       0    1323
23               RAJKUMAR S   ECE     E8EC182     0       0    1302
24                 ROSHNA N    IT     E8IT098     0       0    1205
25           SAI KRISHNAN V   ECE     E8EC007     0       0    1203
26              !*$#@Z: :*!   CSE     E8CS075     0       0    1185
27                SOWMIYA S    IT     E8IT099     0       0    1171
28      MANJU BHARGHAVI V R   CSE     E8CS112     0       0    1158
29           ADITHYA.R #BTP   CSE     E8CS071     0       0    1154
30               MANO RAM S  PROD     E8PR009     0       0    1148
31       << ARUN KUMAR D >>   CSE     E8CS162     0       0    1145
32            MOHAMED ASHIK   ECE     E8EC015     0       0    1141
33                RUBASRI S   CSE     E8CS118     0       0    1128
34       RAJA SELVA KUMAR I    IT     E8IT101     0       0    1095
35                SATHISH G   ECE     E8EC112     0       0    1049
36             VIJAY BABU V    IT     E8IT072     0       0    1037
37                 ENIYAN T   CSE     E8CS101     0       0    1035
38              SIVAKUMAR R   ECE     E8EC138     0       0    1028
39                  GOKUL N   ECE     E8EC090     0       0    1026
40                ADHARSH S    IT     E8IT087     0       0     977
41           DEEPIKA SREE D    IT     E8IT104     0       0     956
42                KARTHIK K    IT     E8IT083     0       0     947
43     JAYAN KUMAR.E #JK-04   CSE     E8CS138     0       0     936
44              DHARSHINI A   ECE     E8EC122     0       0     913
45              SOWMYAA V R    IT     E8IT050     0       0     911
46             RAM PRASAD J   CSE     E8CS048     0       0     897
47      THAARUN G SRIVATSAV    IT     E8IT068     0       0     894
48       SAI NIKHIL REDDY C   CSE     E8CS053     0       0     889
49                AKSHAYA K   CSE     E8CS025     0       0     876
50           THASHANMOULI N   CSE  9952038493     0       0     876

In [13]:
temp_result=[i[1:] for i in result]
temp_df=pd.DataFrame(temp_result,columns=["Dept","ID","Gold","Silver","Bronze"],index=name)
df.columns.name = 'Rank'
temp_df

                       Dept          ID  Gold  Silver  Bronze
MUKILAN I K             CSE     E8CS129     0       2     966
NATHAN DRAKE $          CSE     E8CS059     0       1    1070
VIKRAM V                CSE     E8CS014     0       1     714
SHIBANIKA R             CSE     E8CS111     0       0    2437
EYUWANKG S SWANKG       CSE     E8CS124     0       0    2219
KARTHIKA A               IT     E8IT079     0       0    2006
SURESH KRISHNAA R       CSE     E8CS005     0       0    1947
VISHWAJITH V            CSE     E8CS094     0       0    1939
PARTHIBARAJ G           CSE     E8CS088     0       0    1895
SAKTHIVELAN S           CSE     E8CS078     0       0    1894
VENKATESH D             CSE     E8CS050     0       0    1690
KARTHIK PRASAD T        CSE     E8CS041     0       0    1678
MADHUMITHA S            CSE     E8CS068     0       0    1549
SANTHOSH T               IT     E8IT005     0       0    1522
VIMAL KUMAR V           CSE     E8CS121     0       0    1512
ANIRUDDH R             PROD     E8PR006     0       0    1488
KAVI KON                CSE     E8CS119     0       0    1480
VISWANATHAN M            IT     E8IT016     0       0    1444
N.MOHAMED SAYHANUDDIN    IT     E8IT061     0       0    1417
VIGNESHWAR B             IT     E8IT019     0       0    1328
NAVIN SK                EEE     E8EE006     0       0    1327
HRITHIK KUMAR V         ECE     E8EC013     0       0    1323
RAJKUMAR S              ECE     E8EC182     0       0    1302
ROSHNA N                 IT     E8IT098     0       0    1205
SAI KRISHNAN V          ECE     E8EC007     0       0    1203
!*$#@Z: :*!             CSE     E8CS075     0       0    1185
SOWMIYA S                IT     E8IT099     0       0    1171
MANJU BHARGHAVI V R     CSE     E8CS112     0       0    1158
ADITHYA.R #BTP          CSE     E8CS071     0       0    1154
MANO RAM S             PROD     E8PR009     0       0    1148
<< ARUN KUMAR D >>      CSE     E8CS162     0       0    1145
MOHAMED ASHIK           ECE     E8EC015     0       0    1141
RUBASRI S               CSE     E8CS118     0       0    1128
RAJA SELVA KUMAR I       IT     E8IT101     0       0    1095
SATHISH G               ECE     E8EC112     0       0    1049
VIJAY BABU V             IT     E8IT072     0       0    1037
ENIYAN T                CSE     E8CS101     0       0    1035
SIVAKUMAR R             ECE     E8EC138     0       0    1028
GOKUL N                 ECE     E8EC090     0       0    1026
ADHARSH S                IT     E8IT087     0       0     977
DEEPIKA SREE D           IT     E8IT104     0       0     956
KARTHIK K                IT     E8IT083     0       0     947
JAYAN KUMAR.E #JK-04    CSE     E8CS138     0       0     936
DHARSHINI A             ECE     E8EC122     0       0     913
SOWMYAA V R              IT     E8IT050     0       0     911
RAM PRASAD J            CSE     E8CS048     0       0     897
THAARUN G SRIVATSAV      IT     E8IT068     0       0     894
SAI NIKHIL REDDY C      CSE     E8CS053     0       0     889
AKSHAYA K               CSE     E8CS025     0       0     876
THASHANMOULI N          CSE  9952038493     0       0     876

In [7]:
b=temp_df['Bronze'].describe()
s=temp_df['Silver'].describe() 
g=temp_df['Gold'].describe()
print(b,s,g)

count      50.000000
mean     1282.540000
std       389.647314
min       714.000000
25%       989.250000
50%      1156.000000
75%      1486.000000
max      2437.000000
Name: Bronze, dtype: float64 count    50.000000
mean      0.080000
std       0.340468
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       2.000000
Name: Silver, dtype: float64 count    50.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
Name: Gold, dtype: float64